const express = require("express");
const fs = require("fs");
const jwt = require("jsonwebtoken");
const request = require("supertest");

process.env.JWT_SECRET = process.env.JWT_SECRET || "test-secret";

const receiptRoutes = require("../../routes/receiptRoutes");
const Institution = require("../../models/Institution");
const Student = require("../../models/Student");
const Fee = require("../../models/Fee");
const FeeAssignment = require("../../models/FeeAssignment");
const Payment = require("../../models/Payment");
const generateReceipt = require("../../utils/receiptGenerator");

const app = express();
app.use(express.json());
app.use("/api/receipts", receiptRoutes);

describe("receipt downloads", () => {
  it("regenerates a branded receipt PDF when the file is missing", async () => {
    const institution = await Institution.create({
      name: "Receipt College",
      code: "RECEIPT",
      branding: {
        primaryColor: "#0f766e",
        receiptFooter: "Official receipt generated by Receipt College."
      }
    });

    const student = await Student.create({
      institutionId: institution._id,
      name: "Student User",
      email: "student@example.com",
      password: "password",
      registrationNo: "STU001",
      className: "10A",
      role: "student"
    });

    const fee = await Fee.create({
      institutionId: institution._id,
      title: "Tuition Fee",
      amount: 25000,
      category: "Tuition",
      dueDate: new Date("2026-12-31")
    });

    const assignment = await FeeAssignment.create({
      institutionId: institution._id,
      studentId: student._id,
      feeId: fee._id,
      dueDate: new Date("2026-12-31"),
      status: "paid"
    });

    const payment = await Payment.create({
      institutionId: institution._id,
      studentId: student._id,
      assignmentId: assignment._id,
      amount: 25000,
      mode: "online",
      status: "completed",
      razorpayPaymentId: "pay_receipt_123",
      razorpayOrderId: "order_receipt_123",
      verifiedAt: new Date("2026-05-09T10:00:00.000Z")
    });

    const receiptPath = generateReceipt.getReceiptPath(payment._id);
    if (fs.existsSync(receiptPath)) {
      fs.unlinkSync(receiptPath);
    }

    const token = jwt.sign({ id: student._id, role: student.role }, process.env.JWT_SECRET);

    const res = await request(app)
      .get(`/api/receipts/download/${payment._id}`)
      .set("Authorization", `Bearer ${token}`);

    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("application/pdf");
    expect(fs.existsSync(receiptPath)).toBe(true);
    expect(fs.statSync(receiptPath).size).toBeGreaterThan(1000);

    fs.unlinkSync(receiptPath);
  });
});
