const nodemailer = require("nodemailer");
const path = require("path");

const sendReceiptEmail = async (student, filePath) => {
  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: `"GetPay" <${process.env.EMAIL_USER}>`,
      to: student.email,
      subject: "Payment Receipt - GetPay",
      text: `Hi ${student.name}, your payment was successful.`,
      attachments: [
        {
          filename: path.basename(filePath),
          path: filePath,
        },
      ],
    };

    await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent to ${student.email}`);
  } catch (error) {
    console.error("Error sending email:", error);
  }
};

sendReceiptEmail.sendEmail = async ({ to, subject, text, attachments = [] }) => {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    return { accepted: [to], skipped: true };
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  return transporter.sendMail({
    from: `"GetPay" <${process.env.EMAIL_USER}>`,
    to,
    subject,
    text,
    attachments,
  });
};

sendReceiptEmail.sendPaymentReceipt = sendReceiptEmail;

sendReceiptEmail.sendFeeReminder = async ({ student, fee }) => {
  return sendReceiptEmail.sendEmail({
    to: student.email,
    subject: "Fee Reminder - GetPay",
    text: `Hi ${student.name}, this is a reminder for ${fee.title}.`,
  });
};

module.exports = sendReceiptEmail;
// This function sends a receipt email to the student after a successful payment. It uses Nodemailer to send the email with the receipt PDF attached. The email includes a simple text message and the receipt file generated by the receiptGenerator module.
