const nodemailer = require("nodemailer");
const path = require("path");

const sendReceiptEmail = async (student, filePath) => {
  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: `"GetPay" <${process.env.EMAIL_USER}>`,
      to: student.email,
      subject: "Payment Receipt - GetPay",
      text: `Hi ${student.name}, your payment was successful.`,
      attachments: [
        {
          filename: path.basename(filePath),
          path: filePath,
        },
      ],
    };

    await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent to ${student.email}`);
  } catch (error) {
    console.error("Error sending email:", error);
  }
};

module.exports = sendReceiptEmail;
// This function sends a receipt email to the student after a successful payment. It uses Nodemailer to send the email with the receipt PDF attached. The email includes a simple text message and the receipt file generated by the receiptGenerator module.